export const slackActions = {
  START_FETCHING: 'START_FETCHING',
  FETCHING_MEMBERS_SUCCESS: 'FETCHING_MEMBERS_SUCCESS',
  FETCHING_MEMBERS_FAIL: 'FETCHING_MEMBERS_FAIL',
  KICKING_MEMBER_SUCCESS: 'KICKING_MEMBER_SUCCESS',
  KICKING_MEMBER_FAIL: 'KICKING_MEMBER_FAIL',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
